Traceback (most recent call last):
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/Adhesion/venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
t = c._topographies[1].to_unit("m")
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 1[39m
[32m----> [39m[32m1[39m t = [43mc[49m[43m.[49m[43m_topographies[49m[[32m1[39m].to_unit([33m"[39m[33mm[39m[33m"[39m)

[36mFile [39m[32m~/work/Adhesion/venv/lib/python3.12/site-packages/SurfaceTopography/Container/SurfaceContainer.py:53[39m, in [36mSurfaceContainer.__getattr__[39m[34m(self, name)[39m
[32m     51[39m     [38;5;28;01mreturn[39;00m func
[32m     52[39m [38;5;28;01melse[39;00m:
[32m---> [39m[32m53[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([33m"[39m[33mUnkown attribute [39m[33m'[39m[38;5;132;01m{}[39;00m[33m'[39m[33m and no analysis or pipeline function of this name registered[39m[33m"[39m
[32m     54[39m                          [33m"[39m[33m(class [39m[38;5;132;01m{}[39;00m[33m). Available functions: [39m[38;5;132;01m{}[39;00m[33m"[39m.format(name, [38;5;28mself[39m.[34m__class__[39m.[34m__name__[39m,
[32m     55[39m                                                                       [33m'[39m[33m, [39m[33m'[39m.join([38;5;28mself[39m._functions.keys())))

[31mAttributeError[39m: Unkown attribute '_topographies' and no analysis or pipeline function of this name registered(class LazySurfaceContainer). Available functions: to_zip, bandwidth, suggest_length_unit, autocorrelation, power_spectrum, variable_bandwidth, scale_dependent_statistical_property, ciso_moment, c1d_moment, integrate_psd_from_profile, variance_half_derivative_from_autocorrelation, variance_half_derivative_via_autocorrelation_from_profile

